# Generated by Django 4.1.2 on 2022-11-08 20:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('party', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Party_Invites',
            new_name='Party_Invite',
        ),
        migrations.RemoveField(
            model_name='party',
            name='invites',
        ),
        migrations.AddField(
            model_name='party',
            name='invites',
            field=models.ManyToManyField(blank=True, to='party.party_invites'),
        ),
    ]
