# Generated by Django 4.1.2 on 2022-11-08 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0002_rename_party_invites_party_invite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='invites',
            field=models.ManyToManyField(blank=True, to='party.party_invite'),
        ),
    ]
