# Generated by Django 4.1.2 on 2022-12-05 05:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('party', '0004_party_party_leader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='party_leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='party_leader', to=settings.AUTH_USER_MODEL),
        ),
    ]
