# Generated by Django 4.1.1 on 2023-01-04 06:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('party', '0007_alter_party_member_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='party_leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='party_leader', to='party.party_member'),
        ),
        migrations.AlterField(
            model_name='party_member',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='party_member', to=settings.AUTH_USER_MODEL),
        ),
    ]
