# Generated by Django 4.1.1 on 2023-01-04 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0008_alter_party_party_leader_alter_party_member_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='party_leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='party_leader', to='party.party_member'),
        ),
    ]
