# Generated by Django 4.1.2 on 2022-10-21 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='token',
        ),
    ]
