# Generated by Django 4.1.2 on 2022-10-25 03:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_friendrequest_friendprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendrequest',
            name='from_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_request', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='friendrequest',
            name='to_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_request', to=settings.AUTH_USER_MODEL),
        ),
    ]
