# Generated by Django 4.1.2 on 2022-10-25 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_alter_friendrequest_from_request_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendprofile',
            name='friend_requests',
        ),
        migrations.AddField(
            model_name='friendprofile',
            name='friend_requests',
            field=models.ManyToManyField(blank=True, to='login.friendrequest'),
        ),
    ]
