# Generated by Django 4.1.2 on 2022-10-27 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_remove_friendprofile_friend_requests_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='logged_in',
            field=models.BooleanField(default=False),
        ),
    ]
